name: "Generate Metrix"
description: "Metrix generates a customizable retro-style GIF showcasing GitHub metrics for your GitHub README profile."
author: "joanroig"
branding:
  icon: "terminal"
  color: "green"

inputs:
  # Authentication
  GITHUB_TOKEN:
    description: "GitHub token for authentication"
    required: true
  GITHUB_USERNAME:
    description: "GitHub username for displaying data"
    required: true
  # Fonts
  FONT_SIZE:
    description: "Main font size"
    required: false
    default: "20"
  SYMBOL_FONT_SIZE:
    description: "Symbol font size"
    required: false
    default: "20"
  FONT_PATH:
    description: "Path to the font file"
    required: false
    default: "metrix/assets/MxPlus_IBM_BIOS.ttf"
  SYMBOL_FONT_PATH:
    description: "Path to the symbol font file"
    required: false
    default: "metrix/assets/MxPlus_IBM_BIOS.ttf"
  # Colors
  TEXT_COLOR:
    description: "Color of the text"
    required: false
    default: "random"
  BACKGROUND_COLOR:
    description: "Color of the background"
    required: false
    default: "random"
  MINIMUM_CONTRAST:
    description: "Minimum color contrast"
    required: false
    default: "2"
  # Content Settings
  TEXT:
    description: "Text to display"
    required: false
    default: |
      "{username} GitHub Metrix
      ----------------------

      Joined GitHub: {created_at}
      Followed by: {followers} Users
      Owner of: {total_repos} Repos

      Total Commits: {total_commits}
      Total Stars: {total_stars}

      Data updated: {updated_date}"
  TYPING_CHARACTER:
    description: "Character used for typing effect"
    required: false
    default: "█"
  ACTIVITY_TEXT:
    description: "Text for the activity section"
    required: false
    default: "Last month commit activity:"
  ACTIVITY_DAYS:
    description: "Number of days for activity"
    required: false
    default: "30"
  # Display Settings
  FPS:
    description: "Frames per second for the GIF, recommended to be 50 or below"
    required: false
    default: "50"
  LOOP:
    description: "Enable or disable looping the GIF"
    required: false
    default: "false"
  WIDTH:
    description: "Width of the GIF"
    required: false
    default: "622"
  HEIGHT:
    description: "Height of the GIF"
    required: false
    default: "356"
  # Glitch Effects
  GLITCHES:
    description: "Enable or disable glitches"
    required: false
    default: "true"
  MAX_GLITCHES:
    description: "Maximum amount of glitches at the same time"
    required: false
    default: "4"
  GLITCH_PROBABILITY:
    description: "Probability in percentage of a glitch happening in a frame, between 0 and 100"
    required: false
    default: "3"

runs:
  using: "composite"
  steps:
    - name: Checkout Metrics Code
      uses: actions/checkout@v4
      with:
        repository: joanroig/metrix
        path: metrix

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
      shell: bash

    - name: Install Python Dependencies
      run: pip install -r metrix/requirements.txt
      shell: bash

    - name: Generate GIF
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ inputs.GITHUB_USERNAME }}
        FONT_SIZE: ${{ inputs.FONT_SIZE }}
        SYMBOL_FONT_SIZE: ${{ inputs.SYMBOL_FONT_SIZE }}
        FONT_PATH: ${{ inputs.FONT_PATH }}
        SYMBOL_FONT_PATH: ${{ inputs.SYMBOL_FONT_PATH }}
        TEXT_COLOR: ${{ inputs.TEXT_COLOR }}
        BACKGROUND_COLOR: ${{ inputs.BACKGROUND_COLOR }}
        MINIMUM_CONTRAST: ${{ inputs.MINIMUM_CONTRAST }}
        TEXT: ${{ inputs.TEXT }}
        TYPING_CHARACTER: ${{ inputs.TYPING_CHARACTER }}
        ACTIVITY_TEXT: ${{ inputs.ACTIVITY_TEXT }}
        ACTIVITY_DAYS: ${{ inputs.ACTIVITY_DAYS }}
        FPS: ${{ inputs.FPS }}
        LOOP: ${{ inputs.LOOP }}
        WIDTH: ${{ inputs.WIDTH }}
        HEIGHT: ${{ inputs.HEIGHT }}
        GLITCHES: ${{ inputs.GLITCHES }}
        MAX_GLITCHES: ${{ inputs.MAX_GLITCHES }}
        GLITCH_PROBABILITY: ${{ inputs.GLITCH_PROBABILITY }}
      run: python -u metrix/src/main.py
      shell: bash

    - name: Checkout Executing Repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        path: target

    - name: Move Generated GIF to Executing Repo
      run: |
        mv metrix.gif target/
      shell: bash

    - name: Commit and Push GIF
      run: |
        cd target
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add metrix.gif
        git commit -m "Update GitHub Metrix GIF" || echo "No changes to commit"
        git push
      shell: bash
