# GitHub Action that generates a custom Metrix GIF and pushes it to a separate branch
# Source, documentation and examples: https://github.com/joanroig/metrix

name: Generate Metrix Header

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-metrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Metrix GIF
        uses: joanroig/metrix@main
        with:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: '${{ github.actor }}'
          FONT_SIZE: '36'
          TEXT: 'Metrix'
          ACTIVITY: 'False'
          FPS: '30'
          LOOP: 'true'
          WIDTH: '272'
          HEIGHT: '58'
          GLITCHES: 'false'
          OUTPUT_FILE_PATH: 'metrix-header.gif'

      - name: Commit and Push GIF to separate branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
          # Move GIF to temp location
          mv metrix-header.gif /tmp/
      
          # Checkout or create branch
          git fetch origin metrix-header-only || true
          git switch metrix-header-only || git switch --orphan metrix-header-only
      
          # Move GIF back
          mv /tmp/metrix-header.gif .
      
          git add metrix-header.gif
          git commit -m 'Update Metrix GIF' || echo 'No changes to commit'
          git push origin metrix-header-only
        shell: bash

