name: Generate Metrix

on:
  schedule:
    - cron: '0 0 * * 1' # This is the default schedule, runs every Monday at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-metrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Metrix GIF
        uses: joanroig/metrix@main
        with:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: 'joanroig' # Replace with your GitHub username
          # FONT_PATH: 'assets/MxPlus_IBM_BIOS.ttf'
          # SYMBOL_FONT_PATH: 'assets/MxPlus_IBM_BIOS.ttf'
          TEXT_COLOR: 'red'
          # BACKGROUND_COLOR: 'black'
          # TITLE_SUFFIX: "'s GitHub Metrix"
          # ACTIVITY_TEXT: 'Last month commit activity:'
          # ACTIVITY_DAYS: '30'
          # WIDTH: '622'
          # HEIGHT: '350'
          # GLITCHES: 'true'
